# Generated by Django 5.0.7 on 2024-07-16 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
