# Generated by Django 5.0.4 on 2024-04-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazar',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='mill',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
