# Generated by Django 5.0.4 on 2024-04-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bazar_date_alter_booking_date_alter_mill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mill',
            name='date',
            field=models.DateField(),
        ),
    ]
