# Generated by Django 5.0.4 on 2024-04-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mill_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mill',
        ),
    ]
