# Generated by Django 5.0.4 on 2024-04-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
