# Generated by Django 5.0.4 on 2024-04-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_establish'),
    ]

    operations = [
        migrations.AddField(
            model_name='establish',
            name='reasone',
            field=models.CharField(choices=[('GG', 'Ginger & Garlic'), ('OI', 'Oil'), ('CH', 'Green Chilli'), ('GS', 'Gas'), ('OT', 'Other')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
