# Generated by Django 5.0.4 on 2024-04-22 12:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_others_bill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('date', 'user')},
        ),
    ]
