# Generated by Django 5.0.4 on 2024-06-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_bill_diposit_alter_bill_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='establish',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='mill_cost',
            field=models.IntegerField(default=0),
        ),
    ]
