# Generated by Django 5.0.4 on 2024-06-05 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_bill_establish_alter_bill_mill_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='others',
            name='issue_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
